/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.Validacao;
import dao.CompraDAO;
import entidade.Compra;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class IfrCompra extends javax.swing.JInternalFrame {

    int idCompra = 0;

    /**
     * Creates new form NewJInternalFrame
     */
    public IfrCompra() {
        initComponents();

        // formata campo de data
        Formatacao.formatarData(tffDataCompra);

        // popula Combo Cidade
        new CombosDAO().popularCombo("fornecedor", cmbFornecedor);
        
        new CompraDAO().popularTabela(tblCompra, "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tfdConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        jlbBusca = new javax.swing.JLabel();
        TfdConsultarCompra = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tffDataCompra = new javax.swing.JFormattedTextField();
        cmbFornecedor = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Cadastro - Compra");
        setToolTipText("");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompra);

        jlbBusca.setText("Busca:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfdConsultaLayout = new javax.swing.GroupLayout(tfdConsulta);
        tfdConsulta.setLayout(tfdConsultaLayout);
        tfdConsultaLayout.setHorizontalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBusca)
                .addGap(18, 18, 18)
                .addComponent(TfdConsultarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addGap(26, 26, 26))
        );
        tfdConsultaLayout.setVerticalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfdConsultaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBusca)
                    .addComponent(TfdConsultarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Listagem", tfdConsulta);

        jLabel1.setText("Data");

        jLabel2.setText("Fornecedor");

        tffDataCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffDataCompraFocusLost(evt);
            }
        });

        cmbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tffDataCompra)
                    .addComponent(cmbFornecedor, 0, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tffDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manuntenção", jPanel2);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnConsultar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //declarando as variaveis
       if(ValidarData()){
        String dataCompra = tffDataCompra.getText();
        ComboItem cb = (ComboItem) cmbFornecedor.getSelectedItem();

        //Criação do objeto compra
        Compra compra = new Compra();
        compra.setId(idCompra);
        compra.setData(dataCompra);
        compra.setFornecedor_id(cb.getCodigo());

        //Criação do objeto cidadeDAO
        CompraDAO compraDAO = new CompraDAO();

        
        if (idCompra == 0) {

            if (compraDAO.salvar(compra) == null) {  //Representa uma inserção
                tffDataCompra.setText("");
                cmbFornecedor.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Compra registrada com sucesso!");

                tffDataCompra.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas no registro de Compra");
            }
        } else {
            if (compraDAO.atualizar(compra) == null) {  //Representa uma inserção
                tffDataCompra.setText("");
                cmbFornecedor.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Compra atualizada com sucesso!");

                tffDataCompra.requestFocus();
            }
        }
       }

        idCompra = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ArrayList<Compra> compras = new ArrayList();

        compras = new CompraDAO().consultarTodos();

        for (int i = 0; i < compras.size(); i++) {
            System.out.println("Id: " + compras.get(i).getId());
            System.out.println("data: " + compras.get(i).getData());
            System.out.println("fornecedor: " + compras.get(i).getFornecedor_id());
            System.out.println("");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new CompraDAO().popularTabela(tblCompra, TfdConsultarCompra.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idTabela = String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0));

        idCompra = Integer.parseInt(idTabela);

        Compra compra = new CompraDAO().consultarId(idCompra);

        if (compra != null) {
            jTabbedPane1.setSelectedIndex(1);

            tffDataCompra.setText(compra.getData());
            cmbFornecedor.setSelectedItem(compra.getFornecedor_id());

            tffDataCompra.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id da Compra não encontrado!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idTabela = String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0));

        idCompra = Integer.parseInt(idTabela);
        
        if(new CompraDAO().excluir(idCompra) == null){
            JOptionPane.showMessageDialog(this, "Compra excluida com sucesso!");
            
            new CompraDAO().popularTabela(tblCompra, "");
        } else{
            JOptionPane.showMessageDialog(this, "Problemas aos excluir");
        }
        idCompra = 0;
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tffDataCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffDataCompraFocusLost
        ValidarData();
    }//GEN-LAST:event_tffDataCompraFocusLost
    private boolean ValidarData(){
        if (!Validacao.validarDataFormatada(tffDataCompra.getText())) {
            tffDataCompra.setBackground(Color.YELLOW);
            return false;
        } else {
            tffDataCompra.setBackground(Color.WHITE);
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfdConsultarCompra;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbBusca;
    private javax.swing.JTable tblCompra;
    private javax.swing.JPanel tfdConsulta;
    private javax.swing.JFormattedTextField tffDataCompra;
    // End of variables declaration//GEN-END:variables
}
