/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.ClienteDAO;
import entidade.Cliente;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class IfrCliente extends javax.swing.JInternalFrame {

    int idCliente = 0;

    /*
     * Creates new form NewJInternalFrame
     */
    public IfrCliente() {
        initComponents();

        // formata campo de data
        Formatacao.formatarTelefone(tffTelefoneCliente);
        Formatacao.formatarCpf(tffCpfCliente);

       new ClienteDAO().popularTabela(tblCliente, "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tfdConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jlbBusca = new javax.swing.JLabel();
        TfdConsultarCliente = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tffCpfCliente = new javax.swing.JFormattedTextField();
        tffTelefoneCliente = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tffEmailCliente = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Clientes");
        setToolTipText("");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        jlbBusca.setText("Busca:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfdConsultaLayout = new javax.swing.GroupLayout(tfdConsulta);
        tfdConsulta.setLayout(tfdConsultaLayout);
        tfdConsultaLayout.setHorizontalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBusca)
                .addGap(18, 18, 18)
                .addComponent(TfdConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addGap(26, 26, 26))
        );
        tfdConsultaLayout.setVerticalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfdConsultaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBusca)
                    .addComponent(TfdConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Listagem", tfdConsulta);

        jLabel1.setText("Nome:");

        jLabel3.setText("Email:");

        jLabel2.setText("CPF:");

        tffCpfCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCpfClienteFocusLost(evt);
            }
        });

        tffTelefoneCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffTelefoneClienteFocusLost(evt);
            }
        });

        jLabel4.setText("Telefone:");

        tffEmailCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffEmailClienteFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(tffCpfCliente)
                    .addComponent(tffTelefoneCliente)
                    .addComponent(tffEmailCliente))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tffEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tffCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tffTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manuntenção", jPanel2);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnConsultar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //declarando as variaveis
 
             
        String nomeCliente = tfdNomeCliente.getText();
        String emailCliente = tffEmailCliente.getText();
        String cpfCliente = tffCpfCliente.getText();
        String telefoneCliente = tffTelefoneCliente.getText();
        

        //Criação do objeto compra
        Cliente cliente = new Cliente();
        cliente.setId(idCliente);
        cliente.setNome(nomeCliente);
        cliente.setEmail(emailCliente);
        cliente.setCpf(cpfCliente);
        cliente.setTelefone(telefoneCliente);

        //Criação do objeto cidadeDAO
        ClienteDAO clienteDAO = new ClienteDAO();

        
        if (idCliente == 0) {

            if (clienteDAO.salvar(cliente) == null) {  //Representa uma inserção
                tfdNomeCliente.setText("");
                tffEmailCliente.setText("");
                tffCpfCliente.setText("");
                tffTelefoneCliente.setText("");

                JOptionPane.showMessageDialog(this, "Cliente registrado com sucesso!");

                tfdNomeCliente.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas no registro do Cliente");
            }
        } else {
            if (clienteDAO.atualizar(cliente) == null) {  //Representa uma inserção
                tfdNomeCliente.setText("");
                tffEmailCliente.setText("");
                tffCpfCliente.setText("");
                tffTelefoneCliente.setText("");

                JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso!");

                tfdNomeCliente.requestFocus();
            }
        }

        idCliente = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ArrayList<Cliente> clientes = new ArrayList();

        clientes = new ClienteDAO().consultarTodos();

        for (int i = 0; i < clientes.size(); i++) {
            System.out.println("Id: " + clientes.get(i).getId());
            System.out.println("Nome: " + clientes.get(i).getNome());
            System.out.println("Email: " + clientes.get(i).getEmail());
            System.out.println("CPF: " + clientes.get(i).getCpf());
            System.out.println("Telefone: " + clientes.get(i).getTelefone());
            System.out.println("");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new ClienteDAO().popularTabela(tblCliente, TfdConsultarCliente.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idTabela = String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0));

        idCliente = Integer.parseInt(idTabela);

        Cliente cliente = new ClienteDAO().consultarId(idCliente);

        if (cliente != null) {
            jTabbedPane1.setSelectedIndex(1);

            tfdNomeCliente.setText(cliente.getNome());
            tffEmailCliente.setText(cliente.getEmail());
            tffCpfCliente.setText(cliente.getCpf());
            tffTelefoneCliente.setText(cliente.getTelefone());
            

            tfdNomeCliente.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do Cliente não encontrado!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idTabela = String.valueOf(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0));

        idCliente = Integer.parseInt(idTabela);
        
        if(new ClienteDAO().excluir(idCliente) == null){
            JOptionPane.showMessageDialog(this, "Cliente excluida com sucesso!");
            
            new ClienteDAO().popularTabela(tblCliente, "");
        } else{
            JOptionPane.showMessageDialog(this, "Problemas aos excluir");
        }
        idCliente = 0;
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tffCpfClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCpfClienteFocusLost
        if (!Validacao.validarCPF(Formatacao.removerFormatacao(tffCpfCliente.getText()))) {
            tffCpfCliente.setBackground(Color.YELLOW);
        } else {
            tffCpfCliente.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffCpfClienteFocusLost

    private void tffTelefoneClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffTelefoneClienteFocusLost
        if (!Validacao.validarTelefone(Formatacao.removerFormatacao(tffTelefoneCliente.getText()))) {
            tffTelefoneCliente.setBackground(Color.YELLOW);
        } else {
            tffTelefoneCliente.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffTelefoneClienteFocusLost

    private void tffEmailClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffEmailClienteFocusLost
        if (!Validacao.validarEmail(tffEmailCliente)) {
            tffEmailCliente.setBackground(Color.YELLOW);
        } else {
            tffEmailCliente.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffEmailClienteFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfdConsultarCliente;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbBusca;
    private javax.swing.JTable tblCliente;
    private javax.swing.JPanel tfdConsulta;
    private javax.swing.JTextField tfdNomeCliente;
    private javax.swing.JFormattedTextField tffCpfCliente;
    private javax.swing.JFormattedTextField tffEmailCliente;
    private javax.swing.JFormattedTextField tffTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
