/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.EnderecoDAO;
import entidade.Endereco;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class IfrEndereco extends javax.swing.JInternalFrame {

    int idEndereco = 0;

    /**
     * Creates new form NewJInternalFrame
     */
    public IfrEndereco() {
        initComponents();
        
        
       Formatacao.formatarCep(tffDescricaoCep);

        new EnderecoDAO().popularTabela(tblEndereco, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tfdConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEndereco = new javax.swing.JTable();
        jlbBusca = new javax.swing.JLabel();
        TfdConsultarEndereco = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdDescricaoEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tffDescricaoCep = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Cadastro - Endereço");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEndereco);

        jlbBusca.setText("Busca:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfdConsultaLayout = new javax.swing.GroupLayout(tfdConsulta);
        tfdConsulta.setLayout(tfdConsultaLayout);
        tfdConsultaLayout.setHorizontalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBusca)
                .addGap(18, 18, 18)
                .addComponent(TfdConsultarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisar)
                .addGap(26, 26, 26))
        );
        tfdConsultaLayout.setVerticalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfdConsultaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBusca)
                    .addComponent(TfdConsultarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Listagem", tfdConsulta);

        jLabel1.setText("Endereço");

        tfdDescricaoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDescricaoEnderecoActionPerformed(evt);
            }
        });

        jLabel2.setText("CEP");

        tffDescricaoCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffDescricaoCepFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdDescricaoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(tffDescricaoCep))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdDescricaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tffDescricaoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manuntenção", jPanel2);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnConsultar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tfdDescricaoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDescricaoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDescricaoEnderecoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //declarando as variaveis
        String nomeEndereco = tfdDescricaoEndereco.getText();
        String cepEndereco = tffDescricaoCep.getText();

        //Criação do objeto cidade
        Endereco endereco = new Endereco();
        endereco.setId(idEndereco);
        endereco.setCep(cepEndereco);
        endereco.setDescricao(nomeEndereco);

        //Criação do objeto cidadeDAO
        EnderecoDAO enderecoDAO = new EnderecoDAO();

        if (idEndereco == 0) {

            if (enderecoDAO.salvar(endereco) == null) {  //Representa uma inserção
                tfdDescricaoEndereco.setText("");
                tffDescricaoCep.setText("");

                JOptionPane.showMessageDialog(this, "Endereço registrado com sucesso!");

                tfdDescricaoEndereco.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas no registro de endereço");
            }
        } else {
            if (enderecoDAO.atualizar(endereco) == null) {  //Representa uma inserção
                tfdDescricaoEndereco.setText("");
                tffDescricaoCep.setText("");

                JOptionPane.showMessageDialog(this, "Endereço atualizado com sucesso!");

                tfdDescricaoEndereco.requestFocus();
            }
        }

        idEndereco = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ArrayList<Endereco> enderecos = new ArrayList();

        enderecos = new EnderecoDAO().consultarTodos();

        for (int i = 0; i < enderecos.size(); i++) {
            System.out.println("Id: " + enderecos.get(i).getId());
            System.out.println("Endereço: " + enderecos.get(i).getDescricao());
            System.out.println("Cep: " + enderecos.get(i).getCep());

            System.out.println("");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new EnderecoDAO().popularTabela(tblEndereco, TfdConsultarEndereco.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idTabela = String.valueOf(tblEndereco.getValueAt(tblEndereco.getSelectedRow(), 0));

        idEndereco = Integer.parseInt(idTabela);

        Endereco endereco = new EnderecoDAO().consultarId(idEndereco);

        if (endereco != null) {
            jTabbedPane1.setSelectedIndex(1);

            tfdDescricaoEndereco.setText(endereco.getDescricao());
            tffDescricaoCep.setText(endereco.getCep());

            tfdDescricaoEndereco.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id da cidade não encontrado!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idTabela = String.valueOf(tblEndereco.getValueAt(tblEndereco.getSelectedRow(), 0));

        idEndereco = Integer.parseInt(idTabela);
        
        if(new EnderecoDAO().excluir(idEndereco) == null){
            JOptionPane.showMessageDialog(this, "Endereço excluido com sucesso!");
            
            new EnderecoDAO().popularTabela(tblEndereco, "");
        } else{
            JOptionPane.showMessageDialog(this, "Problemas aos excluir");
        }
        idEndereco = 0;
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tffDescricaoCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffDescricaoCepFocusLost
        if (!Validacao.validarCEP(Formatacao.removerFormatacao(tffDescricaoCep.getText()))) {
            tffDescricaoCep.setBackground(Color.YELLOW);
        } else {
            tffDescricaoCep.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffDescricaoCepFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfdConsultarEndereco;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbBusca;
    private javax.swing.JTable tblEndereco;
    private javax.swing.JPanel tfdConsulta;
    private javax.swing.JTextField tfdDescricaoEndereco;
    private javax.swing.JFormattedTextField tffDescricaoCep;
    // End of variables declaration//GEN-END:variables
}
