 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.FornecedorDAO;
import entidade.Fornecedor;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class IfrFornecedor extends javax.swing.JInternalFrame {

    
    int idFornecedor = 0;
    
    public IfrFornecedor() {
        
        initComponents();
        
        // formata campos: Telefone, Cnpj
        Formatacao.formatarTelefone(tffTelefoneFornecedor);
        Formatacao.formatarCnpj(tffCnpjFornecedor);
        
        new FornecedorDAO().popularTabela(tblFornecedor, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tfdConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        jlbBusca = new javax.swing.JLabel();
        tfdConsultarFornecedor = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdNomeFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tffTelefoneFornecedor = new javax.swing.JFormattedTextField();
        tffCnpjFornecedor = new javax.swing.JFormattedTextField();
        tffEmailFornecedor = new javax.swing.JFormattedTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setTitle("Cadastro - Fornecedor");
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(955, 572));

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFornecedor.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblFornecedor);
        tblFornecedor.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jlbBusca.setText("Busca:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfdConsultaLayout = new javax.swing.GroupLayout(tfdConsulta);
        tfdConsulta.setLayout(tfdConsultaLayout);
        tfdConsultaLayout.setHorizontalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfdConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                    .addGroup(tfdConsultaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(tfdConsultarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        tfdConsultaLayout.setVerticalGroup(
            tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfdConsultaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tfdConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBusca)
                    .addComponent(tfdConsultarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Listagem", tfdConsulta);

        jLabel1.setText("Nome");

        tfdNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeFornecedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Telefone");

        jLabel4.setText("CNPJ");

        tffTelefoneFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffTelefoneFornecedorFocusLost(evt);
            }
        });

        tffCnpjFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCnpjFornecedorFocusLost(evt);
            }
        });
        tffCnpjFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffCnpjFornecedorActionPerformed(evt);
            }
        });

        tffEmailFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffEmailFornecedorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                            .addComponent(tffEmailFornecedor)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tffTelefoneFornecedor)
                            .addComponent(tffCnpjFornecedor))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tffEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tffTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tffCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manuntenção", jPanel2);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnConsultar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new FornecedorDAO().popularTabela(tblFornecedor, tfdConsultarFornecedor.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfdNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeFornecedorActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //declarando as variaveis
        String nomeFornecedor = tfdNomeFornecedor.getText();
        String emailFornecedor = tffEmailFornecedor.getText();
        String telefoneFornecedor = tffTelefoneFornecedor.getText();
        String cnpjFornecedor = tffCnpjFornecedor.getText();

        //Criação do objeto FORNCEDOR
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setId(idFornecedor);
        fornecedor.setNome(nomeFornecedor);
        fornecedor.setEmail(emailFornecedor);
        fornecedor.setTelefone(telefoneFornecedor);
        fornecedor.setCnpj(cnpjFornecedor);
        
        //Criação do objeto cidadeDAO
        FornecedorDAO fornecedorDAO = new FornecedorDAO();

        if (idFornecedor == 0) {

            if (fornecedorDAO.salvar(fornecedor) == null) {  //Representa uma inserção
                tfdNomeFornecedor.setText("");
                tffEmailFornecedor.setText("");
                tffTelefoneFornecedor.setText("");
                tffCnpjFornecedor.setText("");

                JOptionPane.showMessageDialog(this, "Fornecedor registrado com sucesso!");

                tfdNomeFornecedor.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas no registro de fornecedor");
            }
        } else {
            if (fornecedorDAO.atualizar(fornecedor) == null) {  //Representa uma inserção
                tfdNomeFornecedor.setText("");
                tffEmailFornecedor.setText("");
                tffTelefoneFornecedor.setText("");
                tffCnpjFornecedor.setText("");

                JOptionPane.showMessageDialog(this, "Fornecedor atualizado com sucesso!");

                tfdNomeFornecedor.requestFocus();
            }
        }

        idFornecedor = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ArrayList<Fornecedor> fornecedores = new ArrayList();

        fornecedores = new FornecedorDAO().consultarTodos();

        for (int i = 0; i < fornecedores.size(); i++) {
            System.out.println("Id: " + fornecedores.get(i).getId());
            System.out.println("Nome: " + fornecedores.get(i).getNome());
            System.out.println("Email: " + fornecedores.get(i).getEmail());
            System.out.println("Telefone: " + fornecedores.get(i).getTelefone());
            System.out.println("Cnpj: " + fornecedores.get(i).getCnpj());


            System.out.println("");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idTabela = String.valueOf(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 0));

        idFornecedor = Integer.parseInt(idTabela);
        
        if(new FornecedorDAO().excluir(idFornecedor) == null){
            JOptionPane.showMessageDialog(this, "Fornecedor excluido com sucesso!");
            
            new FornecedorDAO().popularTabela(tblFornecedor, "");
        } else{
            JOptionPane.showMessageDialog(this, "Problemas aos excluir");
        }
        idFornecedor = 0;
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idTabela = String.valueOf(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 0));

        idFornecedor = Integer.parseInt(idTabela);

        Fornecedor fornecedor = new FornecedorDAO().consultarId(idFornecedor);

        if (fornecedor != null) {
            jTabbedPane1.setSelectedIndex(1);
            
            
            tfdNomeFornecedor.setText(fornecedor.getNome());
            tffEmailFornecedor.setText(fornecedor.getEmail());
            tffTelefoneFornecedor.setText(fornecedor.getTelefone());
            tffCnpjFornecedor.setText(fornecedor.getCnpj());
                
            tfdNomeFornecedor.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id da cidade não encontrado!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tffCnpjFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffCnpjFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffCnpjFornecedorActionPerformed

    private void tffTelefoneFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffTelefoneFornecedorFocusLost
        if (!Validacao.validarTelefone(Formatacao.removerFormatacao(tffTelefoneFornecedor.getText()))) {
            tffTelefoneFornecedor.setBackground(Color.YELLOW);
        } else {
            tffTelefoneFornecedor.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffTelefoneFornecedorFocusLost

    private void tffCnpjFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCnpjFornecedorFocusLost
        if (!Validacao.validarCNPJ(Formatacao.removerFormatacao(tffCnpjFornecedor.getText()))) {
            tffCnpjFornecedor.setBackground(Color.YELLOW);
        } else {
            tffCnpjFornecedor.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffCnpjFornecedorFocusLost

    private void tffEmailFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffEmailFornecedorFocusLost
        if (!Validacao.validarEmail(tffEmailFornecedor)) {
            tffEmailFornecedor.setBackground(Color.YELLOW);
        } else {
            tffEmailFornecedor.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tffEmailFornecedorFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbBusca;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JPanel tfdConsulta;
    private javax.swing.JTextField tfdConsultarFornecedor;
    private javax.swing.JTextField tfdNomeFornecedor;
    private javax.swing.JFormattedTextField tffCnpjFornecedor;
    private javax.swing.JFormattedTextField tffEmailFornecedor;
    private javax.swing.JFormattedTextField tffTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
