/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.Formatacao;
import apoio.IItemPesquisa;
import apoio.Validacao;
import dao.CompraDAO;
import dao.ItemCompraDAO;
import entidade.Compra;
import entidade.ItemCompra;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class IfrItemCompra extends javax.swing.JInternalFrame implements IItemPesquisa {

    int idItemCompra = 0;
    double total = 0.0;

    /**
     * Creates new form IfrItemCompra
     */
    public IfrItemCompra() {
        initComponents();

        Formatacao.formatarData(tffDataItemCompra);
        tffQuantidadeItem.setText(Formatacao.formatarDecimal(0));
        tffTotal.setText(Formatacao.formatarDecimal(0));

        tfdIdFornecedor.setEditable(false);
        tfdNomeFornecedor.setEditable(false);
        tffTotal.setEditable(false);

        tfdIdProduto.setEditable(false);
        tfdNomeProduto.setEditable(false);
        tfdValorProduto.setEditable(false);
        tffQuantidadeItem.setEditable(false);

        btnLocalizarProduto.setEnabled(false);
        btnRemover.setEnabled(false);
        btnInserir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * // new DlgLocalizar(null, true, this, "item").setVisible(true);
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        tfdNomeFornecedor = new javax.swing.JTextField();
        btnLocalizarCompra = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfdIdProduto = new javax.swing.JTextField();
        tfdNomeProduto = new javax.swing.JTextField();
        btnLocalizarProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tffQuantidadeItem = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tffTotal = new javax.swing.JFormattedTextField();
        tfdIdFornecedor = new javax.swing.JTextField();
        tffDataItemCompra = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdValorProduto = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setText("Fornecedor");

        btnLocalizarCompra.setText("Localizar");
        btnLocalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarCompraActionPerformed(evt);
            }
        });

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto");

        btnLocalizarProduto.setText("Localizar");
        btnLocalizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        tffQuantidadeItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffQuantidadeItemFocusLost(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItem);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        tfdIdFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIdFornecedorActionPerformed(evt);
            }
        });

        tffDataItemCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffDataItemCompraFocusLost(evt);
            }
        });

        jLabel6.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tffTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFechar))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tffQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(474, 474, 474)
                                        .addComponent(btnInserir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(136, 136, 136)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(tfdNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tfdValorProduto))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel6))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addComponent(tffDataItemCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(tfdIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(tfdIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemover)
                                    .addComponent(btnLocalizarProduto)
                                    .addComponent(btnLocalizarCompra))))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffDataItemCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfdNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizarProduto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tffQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserir)
                    .addComponent(btnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarCompraActionPerformed
        new DlgLocalizar(null, true, this, "fornecedor").setVisible(true);
    }//GEN-LAST:event_btnLocalizarCompraActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        if (ValidarData()) {
            Compra compra = new Compra();

            compra.setData(tffDataItemCompra.getText());
            compra.setFornecedor_id(Integer.parseInt(tfdIdFornecedor.getText()));

            String retorno = new CompraDAO().salvar(compra);

            System.out.println("Id Compra retorno: " + retorno);

            if (!retorno.contains("ERROR")) {
                idItemCompra = Integer.parseInt(retorno);

                btnCriar.setEnabled(false);
                btnLocalizarProduto.setEnabled(true);
                btnRemover.setEnabled(true);
                btnInserir.setEnabled(true);
                tffQuantidadeItem.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao criar Compra: " + retorno);
            }
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnLocalizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarProdutoActionPerformed
        new DlgLocalizar(null, true, this, "produto").setVisible(true);
    }//GEN-LAST:event_btnLocalizarProdutoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        ItemCompra itemCompra = new ItemCompra();

        itemCompra.setCompra_id(idItemCompra);
        itemCompra.setProduto_id(Integer.parseInt(tfdIdProduto.getText()));
        itemCompra.setQtde(Double.parseDouble(tffQuantidadeItem.getText().replace(',', '.')));
        itemCompra.setValor(Double.parseDouble(tfdValorProduto.getText().replace("R$", "").replace(',', '.')));

        if (new ItemCompraDAO().salvar(itemCompra) == null) {
            JOptionPane.showMessageDialog(null, "Item inserido.");

            new ItemCompraDAO().popularTabela(tblItem, "", idItemCompra);

            total += (itemCompra.getValor() * itemCompra.getQtde());

            tffTotal.setText(String.valueOf(total));

            tfdIdProduto.setText("");
            tfdNomeProduto.setText("");
            tfdValorProduto.setText("");
            tffQuantidadeItem.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Erro na inserção.");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblItem.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro.");
        } else {
            int idItemC = Integer.parseInt(String.valueOf(tblItem.getValueAt(tblItem.getSelectedRow(), 0)));

            System.out.println("OSIt: " + idItemC);

            String retorno = new ItemCompraDAO().excluir(idItemC);

            if (retorno == null) {
                JOptionPane.showMessageDialog(null, "Registro removido.");

                String qtdeString = String.valueOf(tblItem.getValueAt(tblItem.getSelectedRow(), 3));
                String valorString = String.valueOf(tblItem.getValueAt(tblItem.getSelectedRow(), 4));

                // Remover caracteres não numéricos
                double qtde = Double.parseDouble(qtdeString.replaceAll("[^\\d.]", ""));
                double valor = Double.parseDouble(valorString.replaceAll("[^\\d.]", ""));

                total -= (qtde * valor);

                tffTotal.setText(String.valueOf(total));

                new ItemCompraDAO().popularTabela(tblItem, "", idItemCompra);
            } else {
                JOptionPane.showMessageDialog(null, "Erro: Problemas ao remover registro.\n\n" + retorno);
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tfdIdFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIdFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIdFornecedorActionPerformed

    private void tffDataItemCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffDataItemCompraFocusLost
        ValidarData();
    }//GEN-LAST:event_tffDataItemCompraFocusLost

    private void tffQuantidadeItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffQuantidadeItemFocusLost
          
        String text = tffQuantidadeItem.getText();
        try {
            double quantidade = Double.parseDouble(text);
            DecimalFormat decimalFormat = new DecimalFormat("#,##0.00");
            String formattedText = decimalFormat.format(quantidade);
            tffQuantidadeItem.setText(formattedText);
        } catch (NumberFormatException ex) {
            // Lidar com o caso em que o texto não é um número válido
            tffQuantidadeItem.setText("");
        }
    }//GEN-LAST:event_tffQuantidadeItemFocusLost

private boolean ValidarData(){
        if (!Validacao.validarDataFormatada(tffDataItemCompra.getText())) {
            tffDataItemCompra.setBackground(Color.YELLOW);
            return false;
        } else {
            tffDataItemCompra.setBackground(Color.WHITE);
            return true;
        }
    }
    
    @Override
public void definirValor(String[] valores, String itemPesquisa) {
        if (itemPesquisa.equalsIgnoreCase("fornecedor")) {
            tfdIdFornecedor.setText(valores[0]);
            tfdNomeFornecedor.setText(valores[1]);
        } else if (itemPesquisa.equalsIgnoreCase("produto")) {
            tfdIdProduto.setText(valores[0]);
            tfdNomeProduto.setText(valores[1]);
            tfdValorProduto.setText(valores[2]);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLocalizarCompra;
    private javax.swing.JButton btnLocalizarProduto;
    private javax.swing.JButton btnRemover;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField tfdIdFornecedor;
    private javax.swing.JTextField tfdIdProduto;
    private javax.swing.JTextField tfdNomeFornecedor;
    private javax.swing.JTextField tfdNomeProduto;
    private javax.swing.JTextField tfdValorProduto;
    private javax.swing.JFormattedTextField tffDataItemCompra;
    private javax.swing.JFormattedTextField tffQuantidadeItem;
    private javax.swing.JFormattedTextField tffTotal;
    // End of variables declaration//GEN-END:variables
}
